config/routes.rb
ICS::Application.routes.draw do

  devise_for :users, :controllers => {:sessions => 'sessions'}

  match "/pay" => "adaptive_payments#pay",               :as => :paypal_return
  match "/cancel" => "adaptive_payments#cancel",         :as => :paypal_cancel
  match "/ipn_notify" => "adaptive_payments#ipn_notify", :as => :paypal_ipn

  resources :admins do
    collection do
      get :products
      get :seller
      get :buyer
      get :non_profit
      get :sales
      get :week
      get :review_product
    end
    member do
      put :confirm_product
      put :reject_product
    end
  end
  
  resources :banner_images
  
  resources :causes do
    member do
      get :like
      put :unlike
    end
  end

  resources :categories
  resources :promotion_codes
  resources :invitations
  resources :billing_shipping_addresses

  resources :users do
    resources :contact_shop_owners
    collection do
      get :buyer
      post :buyer_create
      put :username
    end
  end

  resources :line_items do
    resources :orders do
      member do
        put :shipping
      end
      collection do
        get :pay
      end
    end
  end
  resources :carts do
    member do
      get :edit_lineitem
      put :update_lineitem
    end
  end

  resources :products do
    resources :images
    collection do
      get :search
      get :categories
      get :sub_categories
      get :import
      post :upload_products
      get :cause_types
    end
    member do
      get :add_to_cart
      post :create_comment
      get :sort_review
      get :preview_product
      get :review
      post :product_review
      post :favourite
      put :update_favourite
      put :update_mark_favourite
      get :reject
    end
  end

  resources :profiles do
    member do
      get :profile
      put :profile_update
      put :change_password
    end
    collection do
      get :week
      get :non_profit_week
    end
  end

  resources :contacts 
  resources :creatives
  match '/auth/:provider/callback' => 'omniauths#create'
  get '/favourites' => 'products#favourites', :as => :favourites
  get '/category' => 'home#category', :as => :category
  post '/create_alert' => 'home#create_alert', :as => :create_alert
  get '/index' => 'home#index', :as => :index
  get '/search_causes' => 'home#search_causes', :as => :search_causes
  get '/all_causes' => 'home#all_causes', :as => :all_causes
  get '/order_history' => 'profiles#order_history', :as => :order_history
  get '/dashboard' => 'profiles#dashboard', :as => :dashboard
  get '/admin_dashboard' => 'admins#admin_dashboard', :as => :admin_dashboard
  get '/faqs' => 'home#faqs', :as => :faqs
  get '/about_us' => 'home#about_us', :as => :about_us
  get '/delivery_information' => 'home#delivery_information', :as => :delivery_information
  get '/privacy_policy' => 'home#privacy_policy', :as => :privacy_policy
  get '/terms_conditions' => 'home#terms_conditions', :as => :terms_conditions
  post '/contact' => 'home#contact', :as => :contact
  get '/shipping_returns' => 'home#shipping_returns', :as => :shipping_returns
  get '/secure_shopping' => 'home#secure_shopping', :as => :secure_shopping
  get '/how_it_works' => 'home#how_it_works', :as => :how_it_works
  get '/seller/:id' => 'home#seller', :as => :seller
  get '/sell' => 'home#sell', :as => :sell
  get '/cancel_refund_policy' => 'home#cancel_refund_policy', :as => :cancel_refund_policy
  get '/legal_disclaimer' => 'home#legal_disclaimer', :as => :legal_disclaimer
  get '/follow/:id' => "constants#follow", :as => :follow
  get '/favorite/:id' => "constants#favorite", :as => :favorite

  root :to => 'home#index'

  match '/return'=>'carts#return'

  match '/notification' => 'orders#notification'

  match 'orders/:id/refund' => 'orders#refund', :as => 'refund'
  resources :signatures, only: [:create, :new]
  resources :contract_signs, only: [:create, :new]
  resources :icici_signs, only: [:create, :new]
  resources :payments do
    member do
      get :payment_pdf
      get :next_step
      get :thankyou
      get :resend
    end
  end
  resources :icici_payments do
    member do
      get :payment_pdf
      get :resend
    end
  end
  resources :contracts do
    member do
      get :payment_pdf
      get :resend
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :admin?
  def index
    @products = Product.where("status = 'confirmed'").order('product_count DESC')
    @causes = Cause.all
    @email_alert = EmailAlert.new
  end

  def category
    if params[:categories].present?
      @products = Product.where("category_id = ? and status = 'confirmed'", params[:categories])
      #all subcats related to main cat
      @sub_categories = SubCategory.where("category_id = #{params[:categories]}")
    elsif params[:sub_cats].present?
      @products = Product.where("sub_category_id = ? and status = 'confirmed'", params[:sub_cats])
      @sub_sub_categories = SubSubCategory.where("sub_category_id=?", params[:sub_cats])
    elsif params[:child].present?
      @products = Product.where("sub_sub_category_id = ? and status = 'confirmed'", params[:child])
    else
      @products = Product.where("status = 'confirmed'")
    end 
  end

  def create_alert
    @products = Product.where("status = 'confirmed'").order('product_count DESC')
    @causes = Cause.all
    @email_alert = EmailAlert.new(params[:email_alert])
    if @email_alert.save
      UserMailer.alert(@email_alert).deliver
      flash[:success] = "Thank you for subscribing to our mailing list!"
      redirect_to root_path
    else
      render :action => 'index'
    end
  end


  
  def sell
    
  end
  
  def all_causes
    if params[:cause_type]
      @causes = Cause.where("cause_type = '#{params[:cause_type]}'").paginate :page => params[:cause_page], :per_page => 5
    else
      @causes = Cause.paginate :page => params[:cause_page], :per_page => 5
    end
  end
  
  def search_causes
    @causes = Cause.where("title LIKE '%#{params[:query]}%'").paginate :page => params[:cause_page], :per_page => 5
    render :action => 'all_causes'
  end

  def launch
    @email_alert = EmailAlert.new
    render :layout => false
  end
  
  def about_us
  end
  
  def delivery_information
  end
  
  def privacy_policy
  end
  
  def terms_conditions
  end
  
  def contact_us
    @contact = Contact.new
  end

  def legal_disclaimer
  end

  def cancel_refund_policy
  end
  
  def seller
    @user = User.find(params[:id])
    @following = Follow.find_by_user_id_and_receiver_id_and_status(current_user.id, @user.id, 'Follow') if current_user
    @favoritee = FavoriteUser.find_by_user_id_and_receiver_id_and_status(current_user.id, @user.id, 'Favorited') if current_user
    @products = Product.where("user_id = #{@user.id} and status = 'confirmed'").order("created_at Desc")
  end
  
  def contact
    @contact = Contact.new(params[:contact])
    if @contact.save
      UserMailer.contact(@contact).deliver
      respond_to do |format|
        format.js
      end
    end
  end
  
  def shipping_returns
  end
  
  def secure_shopping
  end
  
  def how_it_works
  end
  
  def faqs
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_contact_us.html.erb
<div class="causesBox">
  <h3>Contact Us</h3>
  <p>
    Have a question, concern or just feel like saying hi?<br />
    Fill out the contact form below and we will be in touch with you shortly, or simply email us at <a href="mailto: info@indiancraftstudio.com"><strong>info@indiancraftstudio.com</strong>.</a>
  </p>
  <%= form_for @contact, :url => contact_path, :html => {:method => 'POST'}, :remote => true do |f| %>
    <ul style="margin-left: -36px;width: 355px;padding: 0px 40px;">
      <% @contact.errors.full_messages.each_with_index do |msg, index| %>
        <li style="color: red;line-height: 20px;"><%= index+1 %>. <%= msg %></li>
      <% end %>
    </ul>
    <table style='line-height: 60px;'>
      <tr>
        <td>Name:</td>
        <td><%= f.text_field :name %></td>
      </tr>
      <tr>
        <td>Email:</td>
        <td><%= f.email_field :email %></td>
      </tr>
      <tr>
        <td>Option:</td>
        <td><%= f.select :option, %w(Question Issue) %></td>
      </tr>
      <tr>
        <td>Message:</td>
        <td><%= f.text_area :message, :cols => 20, :rows => 2 %></td>
      </tr>
      <tr>
        <td></td>
        <td><%= f.submit "Contact" %></td>
      </tr>
    </table>
  <% end %>
</div>

app/views/home/all_causes.html.erb
<div class="content">
  <div id="leftColumn">
    <div>
      <%= form_tag search_causes_path, :method => 'get' do %>
        <%= text_field_tag :query, "", :placeholder => "Keywords", :style => 'width: 160px; position: relative;top: -1px;' %>
        <%= submit_tag "Go", :style => 'padding: 4px 5px;' %>
      <% end %>
    </div>
    <br />
    <ul class="list-menuLeft">
      <li class="<%= params[:cause_type] == "Animal Cause" ? "active" : "" %>" style="background-color: #92D0FF;"><%= link_to "Animal Cause", all_causes_path(:cause_type => "Animal Cause"), :style => 'color: white;' %></li>
      <li class="<%= params[:cause_type] == "Human Cause" ? "active" : "" %>" style="background-color: #FF8080;"><%= link_to "Human Cause", all_causes_path(:cause_type => "Human Cause"), :style => 'color: white;' %></li>
      <li class="<%= params[:cause_type] == "Environment Cause" ? "active" : "" %>" style="background-color: #8AD557;"><%= link_to "Environment Cause", all_causes_path(:cause_type => "Environment Cause"), :style => 'color: white;' %></li>
    </ul>
  </div>
  <div id="rightColumn">
    <div class="box-trending">
      <h4>Trending</h4>
      <ul class="list-trending">
        <% Cause.where("title IS NOT NULL").order("count Desc").each do |cause| %>
          <li><%= link_to cause.title, cause_path(cause) %></li>
        <% end %>
      </ul>
    </div>
    <ul class="list-order" style="position: relative; left: -37px; width: 60%; top: -10px;">
      <%= render :partial => '/causes/index' %>
    </ul>
  </div>
  <div class="clearFix"></div>
</div>

app/views/home/all_causes.js.erb
$(".list-order").html('<%= escape_javascript render :partial => '/causes/index' %>');

app/views/home/cancel_refund_policy.html.erb
 <div class="causesBox">
 <h3>Cancellation and refund policy:</h3>
 <p>We will try our best to give superior services and products to our clients.
<br><br>
In case any client is not completely satisfied with our services we can provide a refund within 48 hours from the date and time of sale of the Product in digital delivery category and 48 hours from the time of receipt of product in physical delivery category . The final refunds will be made after deducting the Service Tax and the Hourly charges for the work completed by us.
<br><br>
If paid by credit card, refunds will be issued to the original credit card provided at the time of purchase and in case of Payment Gateway, payments refund will be made to the same account. we depend on payment gateway for processing refunds.
<br><br>
For Digital delivery products cancellation can be done in 48 hours from the receipt of product and the entire amount will be refunded. For physical delivery the cancellation can't be done after the product has been shipped.Please raise all refund requests within 48 hours after that we are not liable to refund any amount and it will be considered as a successful sale.
</p> 
</div>
<style>
  .causesBox p{
    font-size: 15px;
    text-indent: 10px;
  }
</style>

app/views/home/contact_us.html.erb
<div id='contact'>
  <%= render :partial => 'contact_us' %>
</div>

app/views/home/create_alert.js.erb
<% if @email_alert.errors.present? %>
  $('#email_alert').html('<%= escape_javascript render :partial => 'email_alert'%>');
<% else %>
  top.window.location.href = "<%= root_path %>";
<% end %>

app/views/home/how_it_works.html.erb
<div class="causesBox">
  <div class="container-join-form-touts">
    <div class="row-fluid">
      <div class="span12">
        <h2>How It Works?</h2>
      </div>
    </div>
    <div class="row-fluid">
      <div class="span4">
        <h3>Step 1</h3>
        <p>Sign-up for a e-commerce platform account</p>
      </div>
      <div class="span4">
        <h3>Step 2</h3>
        <p>Get approved by the HandiCraft Studios team</p>
      </div>
      <div class="span4">
        <h3>Step 3</h3>
        <p>Set up your e-commerce platform store, select the percentage of donation per product and enable others to make a difference in the world though the sales of your items</p>
      </div>
    </div>
  </div>
</div>
<style>
  .container-join-form-touts {
    overflow-x: hidden;
    overflow-y: hidden;
  }
  .row-fluid {
    width: 100%;
  }


  .row-fluid [class*="span"]:first-child {
    margin-left: 0;
  }
  .row-fluid [class*="span"] {
    min-height: 26px;
  }
  .row-fluid .span12 {
    width: 100%;
    height: 120px;
  }
  .row-fluid [class*="span"] {
    -moz-box-sizing: border-box;
    display: block;
    float: left;
  }

  .container-join-form-touts h2 {
    font-size: 28px;
    margin-top: 15px;
    text-align: center;
  }

  .row-fluid .span4 {
    width: 33%;
  }

</style>

app/views/home/index.html.erb
<div class="sliderLeftColumn">
  <div class="coda-slider" id="lll-id" style="width: 100%;">
    <% @back_images = BannerImage.all %>
    <% for image in @back_images %>
      <div><h2 class="title"><%= link_to image.image_description.slice(0..300), "#", :style => "color: white;" %></h2><img title="" src="<%= image.image.url(:original) %>" width='1000' height="400"/></div>
    <% end %>
  </div>
</div>
<div class="clearFix"></div>
<div class="content">
  <div class="heading-greatWay">
    <span>Great Way To Purchase</span><br>
    <strong><h4>EXQUISITE Handcrafted Products</h4></strong>
    <em>Redfine your personal experience with our unique collection</em>
  </div>
<!--   <div class="commonrow">
    <h1><span>Featured Handicraft</span></h1>
    <div class="list_carousel h225">
      <ul id="caroulproduct1">
        <% for cause in @causes  %>
          <li>
            <%#= link_to image_tag(cause.image.url(:original), :width => "305", :height => "210"), cause_path(cause) %>
            <h4 style="bottom: 0px; left: 0px;"><%#= link_to cause.title, cause_path(cause), :style => 'color: #ffffff;text-decoration: none;' %></h4>
          </li>
        <% end %>
      </ul>
      <div class="clearfix"></div>
      <a id="prev21" class="prev" href="#">&lt;</a>
      <a id="next21" class="next" href="#">&gt;</a>
      <div id="pager21" class="pager"></div>
    </div>
  </div> -->
  <div class="commonrow">
    <h1><span>Featured Products</span></h1>
    <div class="list_carousel">
      <ul id="caroulproduct">
        <% for product in @products  %>
          <li>
            <%= link_to image_tag(product.images.first.image.url(:original), :width => "226", :height => "265"), product_path(product) %>
            <%= render :partial => '/carts/products', :locals => {:product => product} %>
          </li>
        <% end %>
      </ul>
      <div class="clearfix"></div>
      <a id="prev2" class="prev" href="#">&lt;</a>
      <a id="next2" class="next" href="#">&gt;</a>
      <div id="pager2" class="pager"></div>
    </div>
  </div>
  <div class="categoriesCaroul caroulCategories">
    <h1><span>Categories</span></h1>
    <div class="list_carousel">
      <ul id="caroulproduct2">
        <% Product.where("title is not null and status = 'confirmed'").group(:category_id).each do |product|  %>
          <li>
            <%= link_to image_tag(product.images.first.image.url(:original), :width => "217", :height => "170"), category_path(:categories => product.category_id) %>
            <h4><%= product.category.name %></h4>
          </li>
        <% end %>
      </ul>
      <div class="clearfix"></div>
      <a id="prev212" class="prev" href="#">&lt;</a>
      <a id="next212" class="next" href="#">&gt;</a>
      <div id="pager212" class="pager"></div>
    </div>
    <div class="box-newsletter">
      <div class="newsletter-signup">
        <div id='email_alert'>
          <%= render :partial => 'email_alert' %>
        </div>
      </div>
      <div class="column-share">Find us on:</div>
      <ul class="list-media">
        <%= render 'layouts/social' %>
      </ul>
    </div>
  </div>
  <div class="clearFix"></div>
</div>
<script>
  $(function() {
    $('#lll-id').codaSlider({
      autoSlide: true,
      autoHeight: false
    });
  });

  $(function() {
    //	Scrolled by user interaction
    $('#caroulproduct1').carouFredSel({
      prev: '#prev21',
      next: '#next21',
      items: 3,
      pagination: "#pager21",
      auto: false
    });
    $('#caroulproduct2').carouFredSel({
      prev: '#prev212',
      next: '#next212',
      items: 4,
      pagination: "#pager212",
      auto: true,
      auto: {
        pauseOnHover: 'resume'
      }
    });
    $('#caroulproduct').carouFredSel({
      prev: '#prev2',
      next: '#next2',
      pagination: "#pager2",
      items: 4,
      auto: true,
      auto: {
        pauseOnHover: 'resume'
      }
    });
  });
</script>

app/views/home/legal_disclaimer.html.erb
<div class="causesBox">
  <h3>Legal Disclaimer:</h3>
  <p>
The information contained in this website is for general information purposes only.  The information is provided by <a href='http://www.touchsecurecrafts.com'><strong>http://www.touchsecurecrafts.com</strong></a> and while we endeavor to keep the information up to date and correct, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability or availability with respect to the website or the information, products, services, or related graphics contained on the website for any purpose. Any reliance you place on such information is therefore strictly at your own risk.
<br><br>
In no event will we be liable for any loss or damage including without limitation, indirect or consequential loss or damage, or any loss or damage whatsoever arising from loss of data or profits arise out of, or in connection with, the use of this website.
<br><br>
Through this website you are able to link to other websites which are not under the control of <a href='http://www.touchsecurecrafts.com'><strong>http://www.touchsecurecrafts.com</strong></a>, we have no control over the nature, content and availability of those sites. The inclusion of any links does not necessarily imply a recommendation or endorse the views expressed within them.
<br><br>
Every effort is made to keep the website up and running smoothly. However , <a href='http://www.touchsecurecrafts.com'><strong>http://www.touchsecurecrafts.com</strong></a> takes no responsibility for, and will not be liable for, the website being temporarily unavailable due to technical issues beyond our control.

  </p>
</div>
<style>
  .causesBox p{
    font-size: 15px;
    text-indent: 10px;
  }
</style>

app/views/home/secure_shopping.html.erb
<div class="causesBox">
  <h3>Secure Shoping</h3>
  <p>
   we are committed to ensure 100% Purchase Protection through A-to-Z Guarantee for the shopping done on touchsecurecrafts.com<br />
    
  </p>
</div>
<style>
  .causesBox p{
    font-size: 15px;
    text-indent: 10px;
  }

  .causesBox b{
    font-size: 17px;
  }
</style>

app/views/home/sell.html.erb
<article>
  <div class="content">
    <div class="banner-sell">
      <div class="column-questions">
        <ul class="list-buy-sell">
          <li><del>.</del></li>
          <li class="dee">Clothing &amp; Accessories</li>
          <li><del>.</del></li>
          <li class="de">Craft Supplies</li>
          <li><del>.</del></li>
          <li>Handmade Goods</li>
          <li><del>.</del></li>
          <li>Vintage Items</li>
        </ul>
      </div>  
      <div class="column-questions column-sellOnline">  
        <h3>Sell online  your way on </h3>
        <p>"HandiCraft Studios is your place to buy and sell everything from the ordinary to the extraordinary"</p>
        <div class="btn-openIcsShop">
          <%= link_to "<input type='submit' title='Open Indian Carft Studio Shop' value='Open Indian Carft Studio Shop' />".html_safe, new_user_path(:role => 'seller'), :style => 'text-decoration: none;' %>
        </div>
      </div>
      <div class="clearFix"></div>
    </div>
    <div class="box-product">
      <div class="box-product-inn">
        <ul class="list-menuLeft list-education">
          <li><a title="Human handicraft" href="#">Jewellery</a></li>
          <li><a title="Animal handicraft" href="#">Sandalwood Product</a></li>
          <li><a title="Environmental handicraft" href="#">Rosewood Product</a></li>
        </ul>
        <h2>1.Select a Handicraft</h2>
        <p>Every Purchase made from your Movement will donate <strong>$1</strong> to your cause.</p>
      </div>
      <div class="box-product-inn">
        <ul class="list-menuLeft list-education list-movement">
          <li><a title="+ Add to Movement" href="#">+ Add  to Movement</a></li>
        </ul>
        <h2>2.Add Products</h2>
        <p>Hover over a product and click to add to your Movement.</p>
      </div>
      <div class="clearFix"></div>
    </div>
    <div class="box-whysell">
      <h5>Why sell on HandiCraft Studios?</h5>
      <ul class="list-normal list-whysell">
        <li>
          <div class="img-marketplace fright"><img class="fright" alt="" title="" src="/assets/img-marketplace.png"/></div>
          <h2>Be Part of Our Global e-commerce platform</h2>
          <ul class="list-sell">
            <li><a href="#" title="">Lorem Ipsum is simply dummy text of the printing and typesetting industry.</a></li>
            <li><a href="#" title="">Lorem Ipsum has been the industry's standard dummy text</a></li>
            <li><a href="#" title="">Lorem Ipsum is simply dummy text of the printing and typesetting industry.</a></li>
            <li><a href="#" title="">Lorem Ipsum has been the industry's standard dummy text</a></li>
            <li><a href="#" title="">Lorem Ipsum is simply dummy text of the printing and typesetting industry.</a></li>
          </ul>         
        </li>
        <li>
          <div class="img-marketplace fleft"><img class="img-money" alt="" title="" src="/assets/img-money.png" /></div>
          <h2>More Money in Your Pocket</h2>
          <ul class="list-sell">              
            <li><a href="#" title="">Lorem Ipsum is simply dummy text of the printing and typesetting industry.</a></li>
            <li><a href="#" title="">Lorem Ipsum has been the industry's standard dummy text</a></li>
            <li><a href="#" title="">Lorem Ipsum is simply dummy text of the printing and typesetting industry.</a></li>
            <li><a href="#" title="">Lorem Ipsum is simply dummy text of the printing and typesetting industry.</a></li>
            <li><a href="#" title="">Lorem Ipsum has been the industry's standard dummy text</a></li>
          </ul>
        </li>
        <li>
          <div class="img-marketplace fright"><img class="fright" alt="" title="" src="/assets/img-creativity.png"/></div>
          <h3>Express Your Creativity</h3>
          <ul class="list-sell">
            <li><a href="#" title="">Lorem Ipsum is simply dummy text of the printing and typesetting industry.</a></li>
            <li><a href="#" title=""> Lorem Ipsum has been the industry's standard dummy text</a></li>
            <li><a href="#" title="">Lorem Ipsum is simply dummy text of the printing and typesetting industry.</a></li>
            <li><a href="#" title="">Lorem Ipsum is simply dummy text of the printing and typesetting industry.</a></li>
            <li><a href="#" title="">Lorem Ipsum has been the industry's standard dummy text</a></li>
          </ul>
        </li>
        <li>
        </li>
      </ul>     
      <div class="clearFix"></div>
    </div>
    <div class="clearFix"></div>
  </div>
  <div class="row-questions">
    <div class="content">
      <h5>Have More Questions?</h5>
      <div class="column-questions">
        <h2>How do fees work on HandiCraft Studios?</h2>
        <p> Joining and setting up a shop on HandiCraft Studios is free. Each item listing on ICS costs $0.20 USD when the listing is published. A listing lasts for four months or until the item
          is sold. Once a sale occurs, we assess a 3.5% transaction fee on the item's sale price. You have an opportunity to review and accept the fees that you will be charged prior 
          to publishing a listing. </p>
        <p>Fees for listings and transactions are accrued on your monthly HandiCraft Studios bill. At the end of each month we add up all your fees, and we email your monthly statement to you. 
          You must pay your bill by the 15th of the next month using either the credit card on file or PayPal </p>
        <h2>How do fees work on HandiCraft Studios?</h2>
        <p> Joining and setting up a shop on HandiCraft Studios is free. Each item listing on ICS costs $0.20 USD when the listing is published. A listing lasts for four months or until the item
          is sold. Once a sale occurs, we assess a 3.5% transaction fee on the item's sale price. You have an opportunity to review and accept the fees that you will be charged prior 
          to publishing a listing. </p>
      </div>
      <div class="column-questions">
        <h2>How do fees work on HandiCraft Studios?</h2>
        <p> Joining and setting up a shop on HandiCraft Studios is free. Each item listing on ICS costs $0.20 USD when the listing is published. A listing lasts for four months or until the item
          is sold. Once a sale occurs, we assess a 3.5% transaction fee on the item's sale price. You have an opportunity to review and accept the fees that you will be charged prior 
          to publishing a listing. </p>
        <p>Fees for listings and transactions are accrued on your monthly HandiCraft Studios bill. At the end of each month we add up all your fees, and we email your monthly statement to you. 
          You must pay your bill by the 15th of the next month using either the credit card on file or PayPal </p>
        <h2>How do fees work on HandiCraft Studios?</h2>
        <p> Joining and setting up a shop on HandiCraft Studios is free. Each item listing on ICS costs $0.20 USD when the listing is published. A listing lasts for four months or until the item
          is sold. Once a sale occurs, we assess a 3.5% transaction fee on the item's sale price. You have an opportunity to review and accept the fees that you will be charged prior 
          to publishing a listing. </p>
      </div>
    </div>
  </div>
</article>

app/views/home/seller.html.erb
<article>
  <div class="content">
    <div id="leftColumn">
      <div class="menu-categories">
        <h1><span>All Items</span></h1>
        <ul>
          <%= render :partial => '/categories/category' %>
        </ul>
      </div>
      <div class="menu-categories">
        <h1><span>Shop Owner</span></h1>
        <div class="box">
          <div class="thum-shopOwner">
            <%= image_tag(@user.avatar.url(:original), :width => '217', :height => '170') %>
          </div>
          <div class="box-content">
            <p><%= link_to current_user ? (@following.present? ? "Following" : "Follow") : "Follow", follow_path(@user) %>(<%= @user.followers.where("status = 'Follow'").count %>)</p>
            <h5><a title="Roza" href="#"><%= @user.username%></a></h5>
            <h5>Have a question?</h5>
            <p>
              <%= link_to "Contact Shop Owner", new_user_contact_shop_owner_path(@user), :class => 'btn' %>
            </p>
            <div class="clearFix"></div>
          </div>	
        </div>	
      </div>
      <div class="menu-categories">
        <h1><span>Shop Info</span></h1>
        <div class="box">
          <div class="box-content">
            <h5><%= @user.business_name %></h5>
            <div class="clearFix"></div>
          </div>
        </div>	
      </div>
    </div>
    <div id="rightColumn">
      <div class="box-seller">
        <p>
          <%= image_tag(@user.store_image.url(:original), :width => 760, :height => 100) %>
        </p>
        <p style="float: right;">
          <%= link_to current_user ? (@favoritee.present? ? "Favorited" : "Favorite") : "Favorite", favorite_path(@user) %>
        </p>
        <h5><%= link_to @user.business_name, "" %></h5>
        <pre><%= @user.other_info %></pre>
      </div>	
      <div class="list_carousel list-search">
        <ul id="caroulproduct">
          <% for product in @products  %>
            <li style='min-height: 350px;'>
              <%= link_to image_tag(product.images.first.image.url(:original), :width => "200", :height => "150", :style => 'border-radius: 10px;'), product_path(product) %>
              <%= render :partial => '/carts/products', :locals => {:product => product} %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="clearFix"></div>
  </div>
</article>

app/views/home/shipping_returns.html.erb
<div class="causesBox">
  <h3>Shipping Returns</h3>
  <p>
    HandiCraft Studios is responsible for, or involved in the return process raised by the customer.  HandiCraft Studios is expected to provide customers with an exceptional level of service, the shipping return policy is set by each individual delivery vendor and may differ from place to place.  For any questions about returning a specific item, please contact the us directly on support@touchsecurecrafts.com.
  </p>
</div>
<style>
  .causesBox p{
    font-size: 15px;
    text-indent: 10px;
  }
</style>