config/routes.rb
ICS::Application.routes.draw do

  devise_for :users, :controllers => {:sessions => 'sessions'}

  match "/pay" => "adaptive_payments#pay",               :as => :paypal_return
  match "/cancel" => "adaptive_payments#cancel",         :as => :paypal_cancel
  match "/ipn_notify" => "adaptive_payments#ipn_notify", :as => :paypal_ipn

  resources :admins do
    collection do
      get :products
      get :seller
      get :buyer
      get :non_profit
      get :sales
      get :week
      get :review_product
    end
    member do
      put :confirm_product
      put :reject_product
    end
  end
  
  resources :banner_images
  
  resources :causes do
    member do
      get :like
      put :unlike
    end
  end

  resources :categories
  resources :promotion_codes
  resources :invitations
  resources :billing_shipping_addresses

  resources :users do
    resources :contact_shop_owners
    collection do
      get :buyer
      post :buyer_create
      put :username
    end
  end

  resources :line_items do
    resources :orders do
      member do
        put :shipping
      end
      collection do
        get :pay
      end
    end
  end
  resources :carts do
    member do
      get :edit_lineitem
      put :update_lineitem
    end
  end

  resources :products do
    resources :images
    collection do
      get :search
      get :categories
      get :sub_categories
      get :import
      post :upload_products
      get :cause_types
    end
    member do
      get :add_to_cart
      post :create_comment
      get :sort_review
      get :preview_product
      get :review
      post :product_review
      post :favourite
      put :update_favourite
      put :update_mark_favourite
      get :reject
    end
  end

  resources :profiles do
    member do
      get :profile
      put :profile_update
      put :change_password
    end
    collection do
      get :week
      get :non_profit_week
    end
  end

  resources :contacts 
  resources :creatives
  match '/auth/:provider/callback' => 'omniauths#create'
  get '/favourites' => 'products#favourites', :as => :favourites
  get '/category' => 'home#category', :as => :category
  post '/create_alert' => 'home#create_alert', :as => :create_alert
  get '/index' => 'home#index', :as => :index
  get '/search_causes' => 'home#search_causes', :as => :search_causes
  get '/all_causes' => 'home#all_causes', :as => :all_causes
  get '/order_history' => 'profiles#order_history', :as => :order_history
  get '/dashboard' => 'profiles#dashboard', :as => :dashboard
  get '/admin_dashboard' => 'admins#admin_dashboard', :as => :admin_dashboard
  get '/faqs' => 'home#faqs', :as => :faqs
  get '/about_us' => 'home#about_us', :as => :about_us
  get '/delivery_information' => 'home#delivery_information', :as => :delivery_information
  get '/privacy_policy' => 'home#privacy_policy', :as => :privacy_policy
  get '/terms_conditions' => 'home#terms_conditions', :as => :terms_conditions
  post '/contact' => 'home#contact', :as => :contact
  get '/shipping_returns' => 'home#shipping_returns', :as => :shipping_returns
  get '/secure_shopping' => 'home#secure_shopping', :as => :secure_shopping
  get '/how_it_works' => 'home#how_it_works', :as => :how_it_works
  get '/seller/:id' => 'home#seller', :as => :seller
  get '/sell' => 'home#sell', :as => :sell
  get '/cancel_refund_policy' => 'home#cancel_refund_policy', :as => :cancel_refund_policy
  get '/legal_disclaimer' => 'home#legal_disclaimer', :as => :legal_disclaimer
  get '/follow/:id' => "constants#follow", :as => :follow
  get '/favorite/:id' => "constants#favorite", :as => :favorite

  root :to => 'home#index'

  match '/return'=>'carts#return'

  match '/notification' => 'orders#notification'

  match 'orders/:id/refund' => 'orders#refund', :as => 'refund'
  resources :signatures, only: [:create, :new]
  resources :contract_signs, only: [:create, :new]
  resources :icici_signs, only: [:create, :new]
  resources :payments do
    member do
      get :payment_pdf
      get :next_step
      get :thankyou
      get :resend
    end
  end
  resources :icici_payments do
    member do
      get :payment_pdf
      get :resend
    end
  end
  resources :contracts do
    member do
      get :payment_pdf
      get :resend
    end
  end

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, :dependent => :destroy
  has_many :orders, :dependent => :destroy

  attr_accessible :purchased_at, :created_at, :product_id, :ip_address

  has_one :order, :dependent => :destroy

  def add_item(product_id, quantity)
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity += quantity
    else
      current_item = line_items.build(product_id: product_id, quantity: quantity)
    end
    current_item
  end

  def total_price
    line_items.to_a.sum(&:full_price)
  end

  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    @cart = current_cart
    @user_products = current_cart.line_items
    @order = @cart.orders.new(params[:order])
    @comment = Comment.new
  end
  
  def edit_lineitem
    @line_item = LineItem.find(params[:id])
    @comment = Comment.new
    respond_to do |format|
      format.js
    end
  end
  
  def update_lineitem
    @cart = current_cart
    @user_products = current_cart.line_items
    @order = @cart.orders.new(params[:order])
    @line_item = LineItem.find(params[:id])
    @comment = Comment.new
    if params[:line_item][:quantity].to_i == 0
      @line_item.destroy
      respond_to do |format|
        format.js
      end
    else
      if @line_item.product.qty >= params[:line_item][:quantity].to_i
        @line_item.update_attribute(:quantity, params[:line_item][:quantity])
        respond_to do |format|
          format.js
        end
      else
        respond_to do |format|
          format.js
        end
      end
    end
  end

  def destroy
    @cart = LineItem.find(params[:id])
    if @cart.destroy
      if !current_cart.line_items.present?
        current_cart.destroy
        session[:cart] = nil
      end
      redirect_to carts_path
    end
  end


  def return
      @notification = Twocheckout::ValidateResponse.purchase({:sid => SID, :secret => SECRET, :order_number => params['order_number'], :total => params['total'], :key => params['key']})

      @cart = Cart.find(params['merchant_order_id'])
      p "******************************"
      p @notification[:code]
      p "*****************************"
      begin
        if @notification[:code] == "PASS"
          @cart.status = 'success'
          @cart.purchased_at = Time.now
          @order = Order.create(
            :net_payment => params['total'],
            :card_holder_name => params['card_holder_name'],
            :status => 'pending',
            :order_number => params['order_number'],
            :cart_id => params['merchant_order_id'],
            :user_id => current_user.present? ? current_user.id : ''
            )
          session[:cart] = nil
          flash[:notice] = "Your order was successful! We will contact you directly to confirm before delivery."
          redirect_to root_url
        else
          @cart.status = "failed"
          flash[:notice] = "Error validating order, please contact us for assistance."
          redirect_to carts_url
        end
        ensure
        @cart.save
      end
    end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_all_items.html.erb
<%= link_to "<input class='fright' title='Continue Shopping' type='submit' value='Continue Shopping' />".html_safe, '/' %>
<h6><%= current_cart.line_items.count %>  Items in your Cart</h6>
<% if !@user_products.to_a.empty? %>
<% for line_item in @user_products %>
<div class="box-orderfrom">
  <h4>
    <%= link_to "Close", cart_path(line_item), :method => :delete, :confirm => "Are You Sure", :class => "icon-close" %>
    Order from  <%= link_to line_item.product.user.username, seller_path(line_item.product.user) %>
  </h4>
  <div class="checkoutColumn">
    <ul class="list-checkout">
      <%= form_tag pay_line_item_orders_path(line_item.id), :method => 'GET', :id => "submit_cart_#{line_item.id}" do %>


              <% end %>
              <li>
                <div class="row-checkout bold">
                  <div>Order total</div>
                  <div><%= number_to_currency(line_item.full_price) %> USD</div><br>
                  <div>Grand total</div>
                  <div><%= number_to_currency(@cart.total_price) %> USD</div>
                </div>
                <%#= text_field_tag :authentication_code, nil, placeholder: 'Authentication token' %>
                <br/>
                <%#= render :partial => 'payment'%>

                <br/>
                <div id="gateway">
                  <%= form_tag "/payments/index.php", class: 'icici-gateway' do %>
                    <%= hidden_field_tag :amount, @cart.total_price %>
                    <%= submit_tag "Procees Checkout", id: 'checkout-with-icici' %>
                  <% end %>
                </div>

              </li>
            </ul>
            <% if line_item.product.non_profit_cause == 'Any' %>
            <script>
              $("#sub_<%= line_item.id%>").click(function() {
                if ($("#cause_<%=line_item.id%>").val() == '') {
                  alert("Select Non-Profit Cause")
                  return false;
                } else {
                  $("#submit_cart_<%= line_item.id%>").submit();
                }
              });
            </script>
            <% end %>
          </div>
          <ul class="list-order">
            <li>
              <div class="orderThum">
                <%= image_tag(line_item.product.images.first.image.url(:original), :width => '168', :height => '155', :id => "image_#{line_item.id}", :style => 'cursor: pointer;') %>
              </div>
              <script>
                $(document).ready(function() {
                  $("#image_<%= line_item.id %>").mouseover(function() {
                    $("#image_<%= line_item.id %>").css({width: 170, height: 200});
                  });
                  $("#image_<%= line_item.id %>").mouseleave(function() {
                    $("#image_<%= line_item.id %>").css({width: 168, height: 155});
                  });
                });
              </script>
              <ul class="list-orderDetail">
                <li><%= link_to line_item.product.title, product_path(line_item.product) %></li>
                <li>Quantity:
                  <em id='qua'>
                    <%= link_to line_item.quantity, edit_lineitem_cart_path(line_item), :remote => true, :id => 'lll' %>
                  </em>
                  <span id='line_item_quantiy_<%= line_item.id %>'></span>
                </li>
                <li><%= number_to_currency(line_item.product.price) %> USD </li>
                <!-- <li>Donation: <%#= number_to_currency(((line_item.full_price.to_f)*(line_item.product.non_profit_percentage))/100) %> USD </li> -->
              </ul>
            </li>
<!--         <li>
          <div style="position: relative; left: -12px; width: 618px;">
            <div class="thum-productDetail" style="width: 78px;"><canvas id="canvas_<%= line_item.id %>" height="72" width="75"></canvas></div>
            <p style="float: left; margin-top: 17px; width: 218px; margin-left: -2px;"><%#= line_item.product.non_profit_percentage %><%#= "%" %>  of the proceeds <br>will be donated.</p>
            <div class="thum-productDetail" style="width: 170px;">
              <% #if line_item.product.non_profit_cause == "Any" %>
                <%#= image_tag("/assets/icon-dog-foot.png", :width => 50, :height => 50) %>
                <%#= image_tag("/assets/icon-glob.png", :width => 50, :height => 50) %>
                <%#= image_tag("/assets/icon-heart.png", :width => 50, :height => 50) %>
              <%# else %>
                <%#= image_tag(line_item.product.non_profit_cause == 'Animal Cause' ? ("/assets/icon-dog-foot.png") : (line_item.product.non_profit_cause == 'Environmental Cause' ? ("/assets/icon-glob.png") : ("/assets/icon-heart.png")), :width => 72, :height => 74) %>
              <% #end %>
            </div><br />
            <p style="width: 220px; position: relative; left: 210px;"><a title="The United Nations Children's Fund" href="#"><%#= line_item.product.non_profit_cause.capitalize.split("_").join(" ") %></a></p>
          </div>
        </li> -->
        <li>
          <%= form_for @comment, :url => create_comment_product_path(line_item.product, :line_item_id => line_item.id), :method => 'POST', :remote => true do |f| %>
          <span id="error_comment_<%= line_item.id %>" style="color: red;font-weight: bold;font-size: 14px;display: none;">Body Con't be Blank</span>
          <span id="success_comment_<%= line_item.id %>" style="color: green;font-weight: bold;font-size: 14px;display: none;">Successfully Commented.</span>
          <%= f.text_area :body, :rows => 3, :cols => 30, :placeholder => "Enter notes", :id => "body_text_#{line_item.id}" %>
          <%= f.submit "Comment" %>
          <% end %>
        </li>


      </ul>
    </div>
    <% end %>
    <% else %>
    <div style="margin-left: 90px;text-align:center">
      <%= image_tag("/assets/cart.png") %>
    </div>
    <% end %>
    <div class="clearFix"></div>

app/views/carts/_carts.html.erb
<h1 class="icon-productsManagement"></h1>
<div class="tablebox table-orderHistory">
  <div class="row">
    <div class="column">Image</div>
    <div class="column">Item Total</div>
    <div class="column">Full Price</div>
    <div class="column">Qty</div>
    <div class="column">Pay</div>
    <div class="column last">Cancel</div>
  </div>
  <% for line_item in @user_products %>
    <div class="row">
      <div class="column"><%= image_tag(line_item.product.images.first.image.url(:original), :width => '50', :height => '50', :id => "image_#{line_item.id}", :style => 'cursor: pointer;') %></div>
      <div class="column"><%= number_to_currency(line_item.full_price) %></div>
      <div class="column"><%= number_to_currency(line_item.full_price) %></div>
      <div class="column"><%= line_item.quantity %></div>
      <div class="column">
        <%= link_to "Proceed to Checkout", line_item_orders_path(line_item.id), :method => 'POST', :style => 'text-align: center;' %>
      </div>
      <div class="column last">
        <%= link_to "Close", cart_path(line_item), :method => :delete, :confirm => "Are You Sure" %>
      </div>
    </div>
  <% end %>
</div>

app/views/carts/_edit_lineitem.html.erb
<%= form_for @line_item, :url => update_lineitem_cart_path(@line_item), :method => 'PUT', :html => {:id => "search-query"}, :remote => true do |f| %>
  <%= f.text_field :quantity, :style => 'width: 10px;' %>
  <%= f.submit "Add" %>
<% end %>

app/views/carts/_index.html.erb
<div class="content">
  <div id='all_items'>
    <%= render :partial => 'all_items'%>
  </div>
</div>

app/views/carts/_payment.html.erb
<% @params = {'sid' => SID, 'mode' => '2CO', 'merchant_order_id' => current_cart.id} %>


<% i=0 %>
<% for line_item in current_cart.line_items %>
    <% @params['li_'+i.to_s+'_product_id'] = line_item.product.id.to_s %>
    <% @params['li_'+i.to_s+'_name'] = line_item.product.title %>
    <% @params['li_'+i.to_s+'_price'] = line_item.product.price %>
    <% @params['li_'+i.to_s+'_quantity'] = line_item.quantity.to_s %>
    <% i+=1 %>
<% end %>

<% @form = Twocheckout::Checkout.form(@params, "Checkout with 2Checkout") %>
<%p @form %>
<%= @form.html_safe %>

app/views/carts/_products.html.erb
<div>
  <h4><%= product.title.truncate(50, separator: ' ') %></h4>
  <p>Seller: <%= link_to product.sell_name.present? ? product.sell_name.truncate(22) : product.user.username.truncate(22), seller_path(product.user.id) %></p>
  <span><%= number_to_currency(product.price) %></span>
  <!-- <div class="offer"><%#= product.non_profit_percentage %><%= "%" %></div> -->
</div>
<%= link_to "<input type='submit' title='More Info' value='More Info' />".html_safe, product_path(product), :style => 'text-decoration: none;' %>
<%= link_to "<input type='submit' title='Add To Cart' value='Add To Cart' />".html_safe, add_to_cart_product_path(product, :qty => 1), :style => 'text-decoration: none;' %><br /><br /><br />

app/views/carts/edit_lineitem.js.erb
$('#qua').hide();
$('#line_item_quantiy_<%= @line_item.id %>').html('<%= escape_javascript render :partial => 'carts/edit_lineitem' %>');

app/views/carts/index.html.erb
<%= render :partial => 'index' %>

app/views/carts/update_lineitem.js.erb
$("#all_items").html('<%= escape_javascript render :partial => 'carts/all_items'%>');