config/routes.rb
ICS::Application.routes.draw do

  devise_for :users, :controllers => {:sessions => 'sessions'}

  match "/pay" => "adaptive_payments#pay",               :as => :paypal_return
  match "/cancel" => "adaptive_payments#cancel",         :as => :paypal_cancel
  match "/ipn_notify" => "adaptive_payments#ipn_notify", :as => :paypal_ipn

  resources :admins do
    collection do
      get :products
      get :seller
      get :buyer
      get :non_profit
      get :sales
      get :week
      get :review_product
    end
    member do
      put :confirm_product
      put :reject_product
    end
  end
  
  resources :banner_images
  
  resources :causes do
    member do
      get :like
      put :unlike
    end
  end

  resources :categories
  resources :promotion_codes
  resources :invitations
  resources :billing_shipping_addresses

  resources :users do
    resources :contact_shop_owners
    collection do
      get :buyer
      post :buyer_create
      put :username
    end
  end

  resources :line_items do
    resources :orders do
      member do
        put :shipping
      end
      collection do
        get :pay
      end
    end
  end
  resources :carts do
    member do
      get :edit_lineitem
      put :update_lineitem
    end
  end

  resources :products do
    resources :images
    collection do
      get :search
      get :categories
      get :sub_categories
      get :import
      post :upload_products
      get :cause_types
    end
    member do
      get :add_to_cart
      post :create_comment
      get :sort_review
      get :preview_product
      get :review
      post :product_review
      post :favourite
      put :update_favourite
      put :update_mark_favourite
      get :reject
    end
  end

  resources :profiles do
    member do
      get :profile
      put :profile_update
      put :change_password
    end
    collection do
      get :week
      get :non_profit_week
    end
  end

  resources :contacts 
  resources :creatives
  match '/auth/:provider/callback' => 'omniauths#create'
  get '/favourites' => 'products#favourites', :as => :favourites
  get '/category' => 'home#category', :as => :category
  post '/create_alert' => 'home#create_alert', :as => :create_alert
  get '/index' => 'home#index', :as => :index
  get '/search_causes' => 'home#search_causes', :as => :search_causes
  get '/all_causes' => 'home#all_causes', :as => :all_causes
  get '/order_history' => 'profiles#order_history', :as => :order_history
  get '/dashboard' => 'profiles#dashboard', :as => :dashboard
  get '/admin_dashboard' => 'admins#admin_dashboard', :as => :admin_dashboard
  get '/faqs' => 'home#faqs', :as => :faqs
  get '/about_us' => 'home#about_us', :as => :about_us
  get '/delivery_information' => 'home#delivery_information', :as => :delivery_information
  get '/privacy_policy' => 'home#privacy_policy', :as => :privacy_policy
  get '/terms_conditions' => 'home#terms_conditions', :as => :terms_conditions
  post '/contact' => 'home#contact', :as => :contact
  get '/shipping_returns' => 'home#shipping_returns', :as => :shipping_returns
  get '/secure_shopping' => 'home#secure_shopping', :as => :secure_shopping
  get '/how_it_works' => 'home#how_it_works', :as => :how_it_works
  get '/seller/:id' => 'home#seller', :as => :seller
  get '/sell' => 'home#sell', :as => :sell
  get '/cancel_refund_policy' => 'home#cancel_refund_policy', :as => :cancel_refund_policy
  get '/legal_disclaimer' => 'home#legal_disclaimer', :as => :legal_disclaimer
  get '/follow/:id' => "constants#follow", :as => :follow
  get '/favorite/:id' => "constants#favorite", :as => :favorite

  root :to => 'home#index'

  match '/return'=>'carts#return'

  match '/notification' => 'orders#notification'

  match 'orders/:id/refund' => 'orders#refund', :as => 'refund'
  resources :signatures, only: [:create, :new]
  resources :contract_signs, only: [:create, :new]
  resources :icici_signs, only: [:create, :new]
  resources :payments do
    member do
      get :payment_pdf
      get :next_step
      get :thankyou
      get :resend
    end
  end
  resources :icici_payments do
    member do
      get :payment_pdf
      get :resend
    end
  end
  resources :contracts do
    member do
      get :payment_pdf
      get :resend
    end
  end

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :amount, :product_name, :customer_name,:is_signed, :date_of_birth, :address, :city, :state, :post_code, :country, :phone, :email, :card_number, :card_expiry, :card_cvv,:token,:ip_address,:government_id
  has_one :sign, :dependent => :destroy
  validates :amount, :product_name, :customer_name, :address, :city, :state, 
            :post_code, :country,  :phone, :card_expiry,  
            :date_of_birth, presence: true
  validates :amount,  numericality: { only_float: true }
  validates :email, presence: true,
                    :format => { :with => /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/ ,
                    :message => 'is invalid!'},
                    :on => :create
  
def self.search(search)
  if search
     find(:all, :conditions => ['customer_name LIKE ?', "%#{search}%"])
  else
    :all
  end
end


end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_filter :payment, only: [:payment_pdf,:edit,:destroy,:update, :show,  :next_step, :thankyou]
  before_filter :verify_token, only: [:show,:payment_pdf]
  before_filter :require_http_for_admin, :only => ['index']
  def new
    @payment = Payment.new
  end

  def create
    @payment = Payment.new(params[:payment])
    @payment.token = generated_token
    if @payment.save
      # send email with the link to sign the payment
      #PaymentMailer.payment_confirmation(@payment).deliver
      redirect_to payment_url(@payment, signature_token: @payment.token)
      #redirect_to "/payments/index.php?amount=#{@payment.amount}"
    else
      # gflash :now, error: @payment.errors.full_messages.join("<br/>").html_safe
      render :new
    end
  end

  def index
    if !(params[:search].present? or params[:from_date].present?)
      @payments ||= Payment.order("created_at Desc").paginate :page => params[:federal_page], :per_page => 20
    elsif params[:search].present?
      @payments = Payment.where("email LIKE (?) OR customer_name LIKE (?) OR card_number LIKE (?)", "%#{params[:search]}%","%#{params[:search]}%","%#{params[:search]}").order("created_at Desc").paginate :page => params[:federal_page], :per_page => 20
    elsif params[:from_date].present?
      @payments = Payment.where("date(created_at) BETWEEN '#{params[:from_date]}' AND '#{params[:end_date]}'").order("created_at Desc").paginate :page => params[:federal_page], :per_page => 20
    else
      @payments = []
    end
    render :layout => false
  end
  
  def resend
    @payment = Payment.find(params[:id])
    PaymentMailer.payment_confirmation(@payment).deliver
    redirect_to payments_path
  end

  def edit

  end

  def update

    if @payment.update_attributes(params[:payment])
      redirect_to payment_url(@payment,signature_token: @payment.token)
    else
      render :edit
    end
  end

  def show
    @signature = Sign.new(payment_id: payment.id)
  end

  def payment_pdf
    render pdf: "#{@payment.product_name}"
  end

  def next_step
  end

  def thankyou
  end

  def destroy
    @payment.destroy
    redirect_to payments_path
  end

  private

  def payment
    @payment = Payment.find(params[:id])
  end

  def verify_token
    unless payment.token == params[:signature_token]
      #  gflash error: 'Unauthorized access!!'
      redirect_to root_path
    end
  end


end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<% if @payment.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @payment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <div class="input-group">
      <span class="input-group-addon glyphicon glyphicon-shopping-usd">$</span>
      <%= f.text_field :amount, placeholder: "amount", class: "form-control input-lg required" %>
      <span class="input-group-addon">.00</span>
    </div><br/>

    <div class="input-group">
      <span class="input-group-addon glyphicon glyphicon-shopping-cart"><i class="fa fa-shopping-cart"></i></span>
      <%= f.text_field :product_name, placeholder: "ProductName", class: "form-control input-lg required" %>
    </div><br/>

    <div class="input-group">
      <span class="input-group-addon glyphicon glyphicon-user"><i class="fa fa-user"></i></span>
      <%= f.text_field :customer_name, placeholder: "Customer Name", class: "form-control input-lg required" %>
    </div><br/>

    <div class="input-group">
      <span class="input-group-addon glyphicon glyphicon-calendar"><i class="fa fa-calendar"></i></span>
      <%#= f.text_field :date_of_birth, as: :string, input_html: { class: "datepicker" }, placeholder: "Date of Birth",:id => "datepicker", class: "form-control input-lg required" %>
      <%= f.date_select("date_of_birth", {:order => [:day, :month, :year], :end_year => Time.now.strftime('%Y').to_i - 70,  :start_year => Time.now.strftime('%Y').to_i, :use_month_numbers => true}) %>
    </div><br/>

<div class="input-group">
    <span class="input-group-addon glyphicon glyphicon-home"><i class="fa fa-home"></i></span>
    <%= f.text_field :address, class: "form-control input-lg required", placeholder: "Address" %>
  </div><br/>

  <div class="input-group">
    <span class="input-group-addon glyphicon glyphicon-road"><i class="fa fa-road"></i></span>
    <%= f.text_field :city, placeholder: "City", class: "form-control input-lg required" %>

  </div><br/>

  <div class="input-group">
    <span class="input-group-addon glyphicon glyphicon-globe"><i class="fa fa-globe"></i></span>
    <%= f.text_field :state, placeholder: "State", class: "form-control input-lg required" %>
  </div><br/>

  <div class="input-group">
    <span class="input-group-addon glyphicon glyphicon-globe"><i class="fa fa-globe"></i></span>
    <%= f.text_field :post_code, placeholder: "Postcode", class: "form-control input-lg required" %>
  </div><br/>

  <div class="input-group">
    <span class="input-group-addon glyphicon glyphicon-flag"><i class="fa fa-flag"></i></span>
    <%= f.country_select :country, placeholder: "Country", class: "form-control input-lg required", prompt: "Select Country" %>

  </div><br/>

  <div class="input-group">
    <span class="input-group-addon glyphicon glyphicon-phone"><i class="fa fa-phone"></i></span>
    <%= f.text_field :phone, placeholder: "Phone", class: "form-control input-lg required" %>
  </div><br/>

  <div class="input-group">
    <span class="input-group-addon glyphicon glyphicon-envelope"><i class="fa fa-envelope"></i></span>
    <%= f.text_field :email, placeholder: "Email", class: "form-control input-lg required" %>
  </div><br/>

  <div class="input-group">
    <span class="input-group-addon glyphicon glyphicon-credit-card"><i class="fa fa-credit-card"></i></span>
    <%= f.text_field :card_number, placeholder: "Enter your last 4 digits of card ", class: "form-control input-lg required" %>
  </div><br/>

  <div class="input-group card_cvv">
    <span class="input-group-addon glyphicon glyphicon-calendar"><i class="fa fa-list-alt"></i></span>
     <%= f.text_field :card_expiry, placeholder: "MM/YY", class: "form-control input-lg required" %>
    <%#= f.date_select :card_expiry, :discard_day => true, :start_year => Date.today.year, :end_year => (Date.today.year+10), :use_month_numbers => true %>


  </div><br/>


<div class="input-group card">
 <span class="input-group-addon glyphicon glyphicon-calendar"><i class="fa fa-list-alt"></i></span>
 <%= f.text_field :government_id, placeholder: "Any Government ID",:class => "form-control input-lg" %>
</div><br/>

  
</div>

<%= f.hidden_field :ip_address, :value => request.remote_ip %>

<%= f.submit "Submit", class: 'btn btn-sm btn-primary' %>
<% if current_user %>
<%= link_to 'View All Payments', payments_path, class: 'btn btn-sm btn-default pull-right' %>
<% end %>

<style>
  .input-group-addon {
    background-color: #eeeeee;
    border: 1px solid #cccccc;
    border-radius: 4px;
    color: #555555;
    font-size: 14px;
    font-weight: normal;
    line-height: 1;
    padding: 6px 12px;
    text-align: center;
  }

/*.
.ui-datepicker-month
{
  min-width: 20px;

}

.ui-datepicker-year
{
  min-width: 20px;

}
*/



#payment_card_expiry_1i,#payment_date_of_birth_3i,#payment_card_expiry_2i,#payment_date_of_birth_2i,#payment_date_of_birth_1i

{
  min-width: 60px;
}

.error{
    color:#9e2106;
    background: none;
}
</style>
<script>
  $(function() {
    $( "#datepicker" ).datepicker(
    {
      dateFormat: 'dd-mm-yy',
      todayHighlight: true,
      todayBtn: 'linked',
      autoclose: true,
      maxDate: 0,
      changeMonth: true,
      changeYear: true

    }

    );
  });

    $('#cvvForm').validate();
</script>

app/views/payments/_index.html.erb
<br />
<div class="panel panel-info">
    <div class="panel-heading clearfix">
        <div class="btn-group pull-right" style="right: -440px;">
            <%= link_to "<i class='glyphicon glyphicon-plus'></i> New Payment".html_safe, new_payment_path,  class: 'btn btn-sm btn-primary pull-right' %>
          </div>
      </div>
      <div class="panel-body">
          <table class="table table-condensed">
              <thead>
                  <tr>
                      <th></th>
                      <th> CustomerName </th>
                      <th>Created At</th>
                      <th> amount </th>
                      <th> ProductName </th>
                      <th> Address</th>
                      <th> Phone</th>
                      <th> Email</th>
                      <th> CardNumber </th>
                      <th></th>
                      <th></th>
                  </tr>
              </thead>

              <tbody>
                  <% @payments.each do |payment| %>
                    <tr>
                        <td>
                            <span class="glyphicon glyphicon-<%= payment.is_signed ? 'ok text-success' : 'remove text-danger' %>"></span>
                        </td>
                        <td><%= payment.customer_name %></td>
                        <td><%= payment.created_at.strftime("%Y-%m-%d") %> </td>
                        <td><%= number_to_currency(payment.amount) %></td>
                        <td><%= payment.product_name %></td>
                        <td><%= payment.address %></td>
                        <td><%= payment.phone %></td>
                        <td><%= payment.email %> </td>
                        <td>***<%= payment.card_number[-4..-1] %> </td>
                        <td>
                            <% if payment.is_signed && payment.try(:sign).present? %>
                              <%= link_to "<i class='glyphicon glyphicon-save'></i>".html_safe, payment_pdf_payment_path(payment, signature_token: payment.token), class: 'btn btn-xs btn-primary', target: "_blank"  %>
                              <% else %>
                                <%= link_to "<i class='glyphicon glyphicon-send'></i>".html_safe, resend_payment_path(payment), class: 'btn btn-xs btn-danger' %>
                                <% end %>
                            </td>
                            <td>
                                <%= link_to "<i class='glyphicon glyphicon-trash'".html_safe, payment_path(payment), method: :delete, data: { confirm: 'Are you sure want to delete?' }, class: 'btn btn-xs btn-danger' %>
                              </td>
                          </tr>
                        <%end%>
                    </tbody>
                </table>
            </div>
            <div class="panel-footer">
                <%= will_paginate @payments, :param_name => 'federal_page' %>
            </div>
        </div>

app/views/payments/_signature_form.html.erb
<div class="modal-header">
  <h2>Signature Form</h2>
</div>

<%= simple_form_for @signature, url: signatures_path, method: :post do |f| %>
  <div class="modal-body">
<div class="borderd">
  <canvas class="pad" width="350" height="100"></canvas>
</div>
<%= f.hidden_field :signature, class: 'output' %>
<%= f.hidden_field :payment_id, value: @payment.id %>
</div>
<%= f.submit 'Done', class: 'btn btn-sm btn-primary' %>

<% end %>


<script>
  $(document).ready(function () {
    $('#new_sign').signaturePad({
      drawOnly: true,
      lineMargin: 0,
      lineTop: 140,
      penColour: '#2D2D2D'
    });
  });
</script>

<style>
.modal-header
{
  border-bottom: 1px solid #e5e5e5;
  min-height: 16.4286px;
  padding: 15px;
}

.modal-body {
    padding: 15px;
    position: relative;
}
/*.borderd
{
  width: 400px
  height: 80px
  padding: 5px
  border: 1px groove #238adb
  margin: auto
}
  */
</style>

app/views/payments/index.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title><%= @site_title || "Touchsecurecrafts" %></title>
        <%= stylesheet_link_tag 'application' %>
        <%= javascript_include_tag 'application' %>
        <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
        <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
        <%= csrf_meta_tags %>
    </head>
    <body style="padding-top: 80px;">
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container-fluid">
                <!-- brand -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse" id="registration-navbar">
                    <ul  class="nav navbar-nav navbar-left">
                        <h2><li><%= link_to "TouchsecureCrafts", "/" %></li></h2>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="btn-sm"><%= link_to "Paymnets", payments_path %></li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="row">
            <div class="container" style="width: 1290px;">
                <div style="position: relative;">
                    <%= form_tag payments_path, method: 'GET' do %>
                      <%= text_field_tag :search,'', placeholder: "#{params[:search] ? params[:search] : 'Search'}", style: "width: 290px; padding: 10px; border: 1px solid lightskyblue; border-radius: 5px;" %>
                      <%= submit_tag "Search", class: 'btn btn-sm btn-primary' %>
                      <% end %>
                  </div>

                  <div style="position: relative;top: -50px;float: right;">
                      <%= form_tag payments_path, method: 'GET' do %>
                        <%= text_field_tag :from_date,'', placeholder: "#{params[:from_date] ? params[:from_date] : 'From Date'}", id: 'from_date', style: "width: 190px; padding: 10px; border: 1px solid lightskyblue; border-radius: 5px;" %>
                        -
                        <%= text_field_tag :end_date,'', placeholder: "#{params[:end_date] ? params[:end_date] : 'End Date'}", id: 'end_date', style: "width: 190px; padding: 10px; border: 1px solid lightskyblue; border-radius: 5px;" %>
                        <%= submit_tag "Search", class: 'btn btn-sm btn-primary' %>
                        <% end %>
                    </div>
                    <div id='payments'>
                        <%= render :partial => 'index' %>
                    </div>
                </div>
            </div>
        </body>
    </html>
    <script>
      $("#from_date, #end_date").datepicker({
          dateFormat: 'yy-mm-dd',
          changeMonth: true,
          changeYear: true,
          maxDate: 0
      });
    </script>

app/views/payments/new.html.erb
<% @page_title = "Payment" %>
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<link href="/assets/font-awesome.min.css" rel="stylesheet">
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<div class="causesBox">
  <div class="col-md-6 col-md-offset-3">
    <div class="panel-heading">
    <h3>Enter Payment Information</h3>
    </div>

    <%= form_for @payment, :url => payments_path, :method => 'POST', :html => {:id => 'cvvForm'} do |f| %>
<%= render :partial => "form", :locals => {:f => f} %>
<%end%>
</div>

app/views/payments/payment_pdf.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Payment Signer</title>
</head>
<%= render :partial => 'signature-css' %>
<%= render :partial => 'signature-js' %>
<body>
  <div class="row">
    <div class="container">
      <div class="col-xs-12 col-sm-10 right-pannel">
        <div class="panel panel-info panel-pdf">
          <!-- panel heading -->
          <div class="panel-heading">
            <h3 class="panel-title">
              Verified Payment
            </h3>
          </div>

          <!-- panel body -->
          <div class="panel-body">
            <div class="row">
              <div class="col-md-9 col-lg-9"> 
                <table class="table table-user-information">
                  <tbody>
                    <tr>
                      <td>Customer Name</td>
                      <td><%= @payment.customer_name %></td>
                    </tr>
                    <tr>
                      <td>Date of birth</td>
                      <td><%= @payment.date_of_birth %></td>
                    </tr>
                    <tr>
                      <td>Customer Email</td>
                      <td><%= @payment.email %></td>
                    </tr>
                    <tr>
                      <td>Amount</td>
                      <td><%= number_to_currency @payment.amount %></td>
                    </tr>
                    <tr>
                      <td>Product Name</td>
                      <td><%= @payment.product_name %></td>
                    </tr>
                    <tr>
                      <td>Address</td>
                      <td><%= @payment.address %></td>
                    </tr>
                    <td>City</td>
                    <td><%= @payment.city %></td>
                  </tr>
                  <td>State</td>
                  <td><%= @payment.state %></td>
                </tr>
                <tr>
                  <td>Postal Code</td>
                  <td><%= @payment.post_code %></td>
                </tr>
                <td>Country</td>
                <td><%= @payment.country %></td>
              </tr>
            </tr>
            <td>Phone</td>
            <td><%= @payment.phone %></td>
          </tr>
        </tr>
        <td>Card Number</td>
        <td>
          <%= @payment.card_number %>                      
        </td>
      </tr>
      <tr>
        <td>Card Expiry</td>
        <td><%= @payment.card_expiry %></td>
      </tr>
      <tr>
        <td>Card CVV</td>
        <td><%= @payment.card_cvv%></td>
      </tr> 
      <tr>
        <td>Ip Adress:</td>
        <td>
          <%= @payment.ip_address %>
        </td>
      </tr>
      <tr>
        <td colspan="2">
          <p class="text-info"> I confirm that I have read all terms and conditions along with other policies mentioned on touchsecurecrafts and authorise them to charge my credit card against products I have already purchased.There is no confusion or any room for dispute.</p>
        </td>
      </tr>
    </tbody>
  </table>
</div>
</div>
</div>

<!-- panel footer -->
<% if @payment.sign.present? %>
<div class="panel-footer clearfix">
  <div class="signature-wrapper">
    <div class="signature-box" id="signature-box">
      <canvas class="pad" width="380" height="100"></canvas>
    </div>
    <span class="signature-date-placeholder">
      <%= @payment.sign.created_at.utc.strftime("%B %d %Y - %H:%M %p") unless @payment.try(:sign).blank? %>
    </span>

    <script>
      $(function() {
        var data = <%= @payment.sign.signature.to_json.html_safe %>;
        $("#signature-box").signaturePad({displayOnly: true}).regenerate(data);
      });
    </script>
  </div>
</div>
</div>
<%end%>
</div>
</div>
</div>
</body>
</html>

app/views/payments/show.html.erb
<div class="causesBox">

  <div class="row">
    <div class="container">

      <div class="col-xs-12 col-sm-10 right-pannel">
       <div class="panel panel-info panel-pdf">
         <h3 class="panel-title">
          Verify & Place Signature
        </h3>
       
        <div class="panel-body">
          <div class="row">
            <b>Customer Name:</b>&nbsp;&nbsp;&nbsp;&nbsp;
            <strong>  <%= @payment.customer_name %></strong>
            <hr/>
            <br/>
            <b>Date of birth:</b>&nbsp;&nbsp;&nbsp;&nbsp;
            <strong>     <%= @payment.date_of_birth.strftime("%d-%m-%Y") if @payment.date_of_birth.present?%>  </strong> 
            <hr/>
            <br/>
            <b>Customer Email:</b>&nbsp;&nbsp;&nbsp;&nbsp;
            <strong>  <%= @payment.email %>  </strong> 
              <hr/>
            <br/>
            <b>Amount:</b></td>&nbsp;&nbsp;&nbsp;&nbsp;
            <strong>  <%= number_to_currency @payment.amount %>  </strong> 
  <hr/>
            <br/>
            <b>Product Name:</b>&nbsp;&nbsp;&nbsp;&nbsp;
            <strong>   <%= @payment.product_name %>  </strong> 
  <hr/>
            <br/>
            <b>Address:</b>&nbsp;&nbsp;&nbsp;&nbsp;
            <strong>   <%= @payment.address %>  </strong>   <hr/>
            <br/>
            <b>City:</b>&nbsp;&nbsp;&nbsp;&nbsp;
            <strong>  <%= @payment.city %>    </strong>   <hr/>
            <br/>
            <b>State:</b>&nbsp;&nbsp;&nbsp;&nbsp;
            <strong>  <%= @payment.state %>    </strong>   <hr/>
            <br/>

            <b>Postal Code:</b>&nbsp;&nbsp;&nbsp;&nbsp;
            <strong>  <%= @payment.post_code %>    </strong>  <hr/> 
            <br/>
            <b>Country:</b>&nbsp;&nbsp;&nbsp;&nbsp;
            <strong>   <%= @payment.country %>  </strong>  <hr/> 
            <br/>
            <b>Phone:</b>&nbsp;&nbsp;&nbsp;&nbsp;
            <strong>  <%= @payment.phone %>  </strong>   <hr/>
            <br/>
            <b>Card Number:</b>&nbsp;&nbsp;&nbsp;&nbsp;
            <strong>    <%= @payment.card_number %>  </strong>  <hr/> 
            <br/>
            <b>Card Expiry:</b>&nbsp;&nbsp;&nbsp;&nbsp;
            <strong>   <%= @payment.card_expiry %></strong>   <hr/>
            <br/>
            <b>Card CVV:</b>&nbsp;&nbsp;&nbsp;&nbsp;
            <strong>  <%= @payment.card_cvv%></strong>   <hr/>
            <br/>
               <p class="text-info"> confirm that I have read all terms and conditions along with other policies mentioned on touchsecurecrafts and authorise them to charge my credit card against products I have already purchased.There is no confusion or any room for dispute.</p>
                      </div>
          </div>

          <!-- panel footer -->
          
          <div class="panel-footer clearfix">
            <div class="signature-wrapper">
              <% if @payment.is_signed && @payment.sign.present? %>
              <%= render 'signature' %>
              <% else %>
              <%= link_to "click here to sign", new_signature_path(:payment_id => @payment.id), :remote => true,:class => "selected_btn" %>|
              <%= link_to "Edit Payment", edit_payment_path(:payment_id => @payment.id),:class => "selected_btn" %>
              <br/>
              <div id="Signature">
                
              </div>
              <% end %>
            </div>
         </div>


        </div>
      </div>
    </div>
  </div>
</div>


<style>
  .text-info {
    color: #31708f;
}
.selected_btn
{
border : solid 2px #ffffff;
  border-radius : 3px;
  moz-border-radius : 3px;
  -webkit-box-shadow : 0px 0px 5px rgba(0,0,0,1.0);
  -moz-box-shadow : 0px 0px 5px rgba(0,0,0,1.0);
  box-shadow : 0px 0px 5px rgba(0,0,0,1.0);
  font-size : 20px;
  color : #d1ff6e;
  padding : 1px 10px;
  background : #053494;
  background : -webkit-gradient(linear, left top, left bottom, color-stop(0%,#053494), color-stop(100%,#addbff));
  background : -moz-linear-gradient(top, #053494 0%, #addbff 100%);
  background : -webkit-linear-gradient(top, #053494 0%, #addbff 100%);
  background : -o-linear-gradient(top, #053494 0%, #addbff 100%);
  background : -ms-linear-gradient(top, #053494 0%, #addbff 100%);
  background : linear-gradient(top, #053494 0%, #addbff 100%);
  filter : progid:DXImageTransform.Microsoft.gradient( startColorstr='#053494', endColorstr='#addbff',GradientType=0 );

}
</style>